const num1 = 10;
const num3 = 30;

console.log(num1);

try { // try es la parte que va intentar ejecutar el c√≥digo
  console.log(num2);
} catch (error) { // catch va a mostrar el error si el try no se ejecuta
  console.log(error);
}

console.log(num3);
